/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package touch.api.integration;

public class App {
   private final Wallet mobileMoneyAccount;
   
   public App(Wallet mobileMoneyAccount) {
	   this.mobileMoneyAccount = mobileMoneyAccount;
   }
    public static void main(String[] args) {
    	App app = new App(new MobileMoneyAccount());
    	app.executesOperations();
        
    }

	public void executesOperations() {
		mobileMoneyAccount.doCashin();
    	mobileMoneyAccount.doCachout();
    	mobileMoneyAccount.dopayment();
	}
    
    
}
